FROM python:3.7-slim

RUN pip install --upgrade pip
RUN pip install pandas
RUN pip install sklearn
RUN pip install fastapi
RUN	pip install pydantic
RUN pip install uvicorn

WORKDIR /usr/app

COPY node1.py ./
COPY diabetes.csv ./

CMD ["uvicorn", "node1:app", "--host", "0.0.0.0", "--port", "80"]
